query productSearch($query: String!) {
  productSearch(query: $query) {
    products {
      cacheId
      categories
      description
      linkText
      productId
      productName
      productReference
      jsonSpecifications
      items {
        itemId
        name
        nameComplete
        complementName
        ean
        productSpecifications {
          fieldName
          fieldValues
        }
        skuSpecifications {
          fieldName
          fieldValues
        }
        images {
          cacheId
          imageId
          imageLabel
          imageTag
          imageUrl
          imageText
        }
        variations {
          name
          values
        }
        sellers {
          sellerId
          sellerName
          commertialOffer {
            teasers {
              name
            }
            Price
            ListPrice
            PriceWithoutDiscount
            RewardValue
            PriceValidUntil
            AvailableQuantity
          }
        }
      }
    }
  }
}
